# http://www.appveyor.com/docs/appveyor-yml

clone_depth: 10

environment:
  matrix:
    - nodejs_version: 6
    - nodejs_version: 8

platform:
  - x64

version: "{build}"
build: off
deploy: off

install:
  - ps: Install-Product node $env:nodejs_version $env:platform

test_script:
  - npm test

cache:
  # global npm cache
  - '%APPDATA%\\npm-cache'
